verbose: false
include: 
  - src/
extension:
  - '.js'
reporter:
  - lcov
  - html
  - text
watermarks:
  statements: [50, 80]
  lines: [50, 80]
  functions: [50, 80]
  branches: [50, 80]
check-coverage: false
